// V15 Vantage — generate v15-vantage/MEDIA-CREDITS.md from the two sources of
// truth, so the public credit ledger cannot drift from what actually ships.
//
// This script did not exist until 2026-08-02. The handoff asserted the ledger
// was "generated from SOURCES.json, so credits cannot drift" — it was in fact
// hand-written, which is exactly how a ledger goes stale without anyone
// noticing. Provenance comes from _brand/photo-set/SOURCES.json; pool
// membership, order and the per-frame credit string come from
// hero-controller.js, because that is the file the browser actually reads.
// Anything in SOURCES.json that is not in the pool is reported as benched
// rather than quietly dropped.
//
// Usage: node credits-v15.mjs [--check]
//   --check exits non-zero if the file on disk differs, for use in an audit.
import { readFile, writeFile } from "fs/promises";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const variant = join(here, "..", "v15-vantage");
const target = join(variant, "MEDIA-CREDITS.md");

const sources = JSON.parse(await readFile(join(here, "..", "_brand", "photo-set", "SOURCES.json"), "utf8"));
const controller = await readFile(join(variant, "hero-controller.js"), "utf8");

// Parse the POOL array out of the controller. Deliberately narrow: it reads the
// object literals between `const POOL = [` and its closing `];` and pulls the
// four fields the ledger needs. If the shape ever changes this throws rather
// than silently emitting a short ledger.
const poolSrc = controller.match(/const POOL = \[([\s\S]*?)\n  \];/);
if (!poolSrc) throw new Error("could not find the POOL array in hero-controller.js");
const pool = [...poolSrc[1].matchAll(/\{([\s\S]*?)\}/g)].map((m) => {
  const field = (k) => (m[1].match(new RegExp(`${k}:\\s*"((?:[^"\\\\]|\\\\.)*)"`)) || [])[1];
  return { file: field("file"), city: field("city"), label: field("label"), credit: field("credit") };
});
if (!pool.length || pool.some((p) => !p.file)) throw new Error("POOL parsed but empty or malformed");

// which page opens on which pool index
const PAGES = [
  ["index.html", "Home"], ["mission.html", "Mission"],
  ["for-clients.html", "For clients"], ["for-students.html", "Students"],
];
const opensOn = new Map();
for (const [file, name] of PAGES) {
  const html = await readFile(join(variant, file), "utf8");
  const m = html.match(/data-hero-start="(\d+)"/);
  if (m) opensOn.set(Number(m[1]), name);
}

const byName = new Map(sources.map((s) => [s.name, s]));
const missing = pool.filter((p) => !byName.has(p.file));
if (missing.length) throw new Error(`pool frames absent from SOURCES.json: ${missing.map((m) => m.file).join(", ")}`);

const shareAlike = (lic) => /BY-SA/i.test(lic || "");
const cityCount = pool.reduce((a, p) => (a[p.city] = (a[p.city] || 0) + 1, a), {});
const origins = [...new Set(pool.map((p) => (byName.get(p.file).licence === "Pexels License" ? "Pexels" : "Wikimedia Commons")))];

const L = [];
L.push("# V15 Vantage — media ledger");
L.push("");
L.push("<!-- GENERATED by tools/credits-v15.mjs from _brand/photo-set/SOURCES.json");
L.push("     and the POOL in v15-vantage/hero-controller.js. Do not edit by hand:");
L.push("     run `node credits-v15.mjs` instead, or the ledger will drift from");
L.push("     the frames the page actually loads. -->");
L.push("");
L.push("Every background in this variant is a **real photograph** of Rotterdam or Delft,");
L.push("licensed for commercial use and credited to the photographer who took it. None is");
L.push("AI-generated. An earlier build of this variant did use generated imagery and");
L.push("disclosed it; that was replaced on 2026-08-01 after board feedback.");
L.push("");
L.push("No photograph here depicts an 180 Degrees Consulting project, client, team or");
L.push("event, and no photographer endorses 180DC Delft–Rotterdam. Each public page names");
L.push("the photographer and licence of the frame on screen, and the credit changes as the");
L.push("visitor browses the pool.");
L.push("");
// Keep the public credit record complete without repeating a changing
// photographer/location label over the hero artwork itself.
L.splice(-5, 5,
  "No photograph here depicts an 180 Degrees Consulting project, client, team or",
  "event, and no photographer endorses 180DC Delft–Rotterdam. The public footer links",
  "to the on-site credit ledger, which records the photographer and licence for every",
  "frame in the pool.",
  ""
);
L.push(`The pool is **${pool.length} frames** — ` +
  Object.entries(cityCount).map(([c, n]) => `${n} ${c}`).join(", ") +
  `. Sources: ${origins.join(" and ")}.`);
L.push("");
L.push("**Licence obligations.** Attribution is required for every CC BY and CC BY-SA");
L.push("frame, and for the share-alike frames the cropped, compressed derivative shipped");
L.push("in `img/` is itself distributed under the same licence. The Pexels License does");
L.push("not compel attribution; these frames are credited anyway, because this site");
L.push("credits every photograph regardless of whether its licence requires it.");
L.push("");

pool.forEach((p, i) => {
  const s = byName.get(p.file);
  const page = opensOn.get(i);
  L.push(`## ${page ? `${page} hero — ` : ""}pool ${i + 1}/${pool.length}${page ? "" : " (reached by cycling)"}`);
  L.push("");
  L.push(`Shipped: \`img/${p.file}.webp\` (plus \`-sm\` 900px and \`-2x\` 2400px tiers, and \`-depth.webp\`)`);
  L.push("");
  L.push(`- Hero label: **${p.label}**`);
  L.push(`- Hero credit line: **${p.credit}**`);
  L.push(`- Work: **${s.work}**`);
  L.push(`- Creator: **${s.photographer}**`);
  L.push(`- Source: ${s.source}`);
  L.push(`- Licence: **${s.licence}** — ${s.licenceUrl}`);
  L.push(`- Original: ${s.originalPx}, cropped to ${s.croppedTo}`);
  L.push(`- Edits: ${s.edits}`);
  if (s.note) L.push(`- Note: ${s.note}`);
  if (shareAlike(s.licence)) L.push(`- **This adaptation remains under ${s.licence}.**`);
  L.push("");
});

const benched = sources.filter((s) => !pool.some((p) => p.file === s.name));
if (benched.length) {
  L.push("## Prepared but not in the pool");
  L.push("");
  L.push("These frames are built and on disk so that reinstating one is a POOL edit in");
  L.push("`hero-controller.js`, not a re-download. They are **not** loaded by any page.");
  L.push("");
  for (const s of benched) {
    L.push(`- **${s.name}** — ${s.work}, ${s.photographer}, ${s.licence}. ${s.source}`);
    if (s.benchedBecause) L.push(`  - Benched because: ${s.benchedBecause}`);
  }
  L.push("");
}

const out = L.join("\n");

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== out) {
    console.error("MEDIA-CREDITS.md is out of date — run: node credits-v15.mjs");
    process.exit(1);
  }
  console.log("MEDIA-CREDITS.md matches SOURCES.json + the pool.");
} else {
  await writeFile(target, out);
  console.log(`wrote ${target}\n  ${pool.length} pooled frames, ${benched.length} benched`);
}
